name: run instascraper.py
run-name: ${{ github.actor }} is posting 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo content
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run file
        run: python instascraper.py
          
      
